// Json Mapping Automatically Generated By JsonToolkit Library for C#
// Diego Trinciarelli 2011
// To use this code you will need to reference Newtonsoft's Json Parser, downloadable from codeplex.
// http://json.codeplex.com/
// 
using System;
using Newtonsoft.Json;

namespace Jarvis.Objects.Reference
{

    [Serializable]
    class IMDB
    {

        public string Title;
        public string Year;
        public string Rated;
        public string Released;
        public string Runtime;
        public string Genre;
        public string Director;
        public string Writer;
        public string Actors;
        public string Plot;
        public string Poster;
        public string ImdbRating;
        public string ImdbVotes;
        public string ImdbID;
        public string Response;

        //Empty Constructor
        public IMDB() { }

        public string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }
        public static IMDB FromJson(string json)
        {
            return JsonConvert.DeserializeObject<IMDB>(json);
        }
        public static IMDB FromQuery(string query)
        {
            return FromJson(new BrowserClient().DownloadString("http://www.imdbapi.com/?t=" + query));
        }
    }

}
//Json Mapping End
