// Json Mapping Automatically Generated By JsonToolkit Library for C#
// Diego Trinciarelli 2011
// To use this code you will need to reference Newtonsoft's Json Parser, downloadable from codeplex.
// http://json.codeplex.com/
// 

using System;
using System.Net;
using Newtonsoft.Json;

namespace Jarvis.Objects
{

    [Serializable]
    public class GoogleVoice
    {

        public string Rnr_xsrf_token;
        public string Standard_email;
        public int App_version;
        public Conversations_response Conversations_response;
        public Account_status Account_status;

        //Empty Constructor
        public GoogleVoice() { }

        public string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }
        private static GoogleVoice FromJson(string json)
        {
            return JsonConvert.DeserializeObject<GoogleVoice>(json);
        }

        public static GoogleVoice Inbox()
        {
            var client = new BrowserClient("www.google.com");
            client.Headers[HttpRequestHeader.Cookie] =
                "gv=DQAAAOoBAACcZaG4tc-bJ07CTlw54dmO5gOnyN1Cr4DcjjsP5H1qWlf4kux1wtePCJTTghFzjHyQHXlyIcc-cgg_ayJRyqibXItVuJF7RKvuIHAenx8rP_-w09KcjTNjgmtb27G2at6p2qhAenHSA953hX_TlT2lvuRr4wU4wqXtbMoxFI4ymAHS1HW1T4Tcd-zjcIndulEcUU2jgoxoXtwAYdFc6Aa-ThFYAJfBAaFHpDtGJ7P5cw8_K5bqTldQvJp33u29YbxuPtPvHnN_kQw2aJsDEUnmqTrHE-BukPqrcMBODWmamSRaFTjlMmAXvXRVi0JA7XpGOV0ri4d4VJuRlIxF_7YOK5ZZbnVW8Db1zE1BLxHBRmdar5Z2WuLaAEXgwf5hQxBioZdavH_BbPnb0d9c7C3_VLFxzaVYo4C7WaMODCVxT11bOSKP9qZV8xRWnT3it8UGo24xrQJaziNPXsPVquyiNx4M0GUErGMP0aqOKy5TsLfT23cd15e7sLwDjDtnwP0CVG43jK6efKL5R1vYBewMr4nHVZLpZBzANVGtm58Mw6y90vBUt4Ve9BvVnyl5J8V6G1o-EFaiZlNo1PynKgft_21RgRoUZjOUSUzLuDYgsz8CMmEjvNG48OBK56i2TuXqGBbKl6SK3qrJq0_KhFLL;Path=/voice;Secure;HttpOnly";

            var json =
                client.PostData(
                    "https://www.google.com/voice/m/x?m=list&l=inbox&o=0&lm=10&v=10", new
                        {
                           m = "list",
                           l = "inbox",
                           lm = 10,
                           v = 10
                        });
            return FromJson(json);

        }
    }


    [Serializable]
    public class Status
    {

        public int Value;

        //Empty Constructor
        public Status() { }

    }


    [Serializable]
    public class Contact
    {

        public object Id;
        public string Phone_number_formatted;
        public string Phone_number;
        public int Phone_type;
        public string Name;

        //Empty Constructor
        public Contact() { }

    }


    [Serializable]
    public class Phone_call
    {

        public string Id;
        public string Message_text;
        public int Status;
        public int Coarse_type;
        public string Did;
        public object Start_time;
        public int Transcript_status;
        public int Type;
        public Contact Contact;

        //Empty Constructor
        public Phone_call() { }

    }


    [Serializable]
    public class Conversation
    {

        public string Id;
        public bool Read;
        public string[] Label;
        public object Conversation_time;
        public Phone_call[] Phone_call;

        //Empty Constructor
        public Conversation() { }

    }


    [Serializable]
    public class Conversations_response
    {

        public Status Status;
        public Conversation[] Conversation;

        //Empty Constructor
        public Conversations_response() { }

    }


    [Serializable]
    public class Status2
    {

        public int Status;

        //Empty Constructor
        public Status2() { }

    }


    [Serializable]
    public class Label
    {

        public object Last_modified_timestamp;
        public string LabelName;
        public int Unread_count;
        public int Total_count;

        //Empty Constructor
        public Label() { }

    }


    [Serializable]
    public class Account_status
    {

        public int Max_balance;
        public string Displayable_max_balance;
        public int Paid_credit;
        public Status2 Status;
        public string Primary_did;
        public string[] Displayable_valid_amount;
        public Label[] Label;
        public string Displayable_account_balance;
        public bool Active_in_use;
        public int Type;
        public int[] Valid_amount;
        public int Account_balance;

        //Empty Constructor
        public Account_status() { }

    }

}
//Json Mapping End
