// Json Mapping Automatically Generated By JsonToolkit Library for C#
// Diego Trinciarelli 2011
// To use this code you will need to reference Newtonsoft's Json Parser, downloadable from codeplex.
// http://json.codeplex.com/
// 

using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using Newtonsoft.Json;

namespace Jarvis.Objects
{

    [Serializable]
    public class GoogleVoice
    {

        public string Rnr_xsrf_token;
        public string Standard_email;
        public int App_version;
        public Conversations_response Conversations_response;
        public Account_status Account_status;

        //Empty Constructor
        public GoogleVoice() { }

        public string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }
        private static GoogleVoice FromJson(string json)
        {
            return JsonConvert.DeserializeObject<GoogleVoice>(json);
        }

        public static GoogleVoice Inbox()
        {

            var request = (HttpWebRequest)WebRequest.Create("https://www.google.com/voice/m/x?m=list&l=inbox&o=0&lm=10&v=10");
            request.Method = "POST";
            string postData = "{\"gvx\":\"NJH5SCksWfGkUHoZRb5oPbgpUnc:1344091762000\"}";
            byte[] byteArray = Encoding.UTF8.GetBytes(postData);
            request.ContentType = "application/x-www-form-urlencoded";
            request.ContentLength = byteArray.Length;

            request.UserAgent =
                "Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16";
            request.Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8";
            request.Referer = "https://www.google.com/voice/m";
            request.Headers[HttpRequestHeader.Cookie] =
                "gv=DQAAAOgAAAC_-od-p66KLRectbr0CbHm9TL7apzK745icVLSN8uiNoD-jN2QCEokOPLL68XvsIkjTUQ2EHmH9ymdny6wq8uXGBxKl7UaHtQMaExRuNrnyYmp2aaNrSDnH23K654Q5NKEcz56YNiCJX-56zi8_AbLm7Gvh0iPhRv-2i4QKWsuJ74SddKTZgILcmkCu-AE9oepBGDSpwelpzGk7ZEKN2mL04xpljgcMpO59H0Bhvo7u0peOHxSvg08xlgYvACGskNiCdCtAilgvaDUs5xBmXqZYr-JZlNNqGXYJ0q4uGR0eyQBXoH-rSkEzl68R4c377k; gvx=NJH5SCksWfGkUHoZRb5oPbgpUnc:1344091762000; PREF=ID=086ea826a1403cc3:U=01b696cd9fcb13c3:FF=4:LD=en:NR=10:TM=1334743545:LM=1344102359:SG=3:S=T7JYnh5pfKgIk0je; NID=62=kbY9N7EqWby0Aq1--c08lEtvwwnV7uJe50_PAgptlYfG-ghf2PBxiiWnpFg3UzhHfbMDwSr_u7Rtld6RJp52pqU_MLDAYDHhsI6ZvFQT1zWj_rHEMx0_U64wLVtONBcz8E8MlBq8UIkOXLdclu8NAVM_OcbWKeVC4P1QZ0nm85yn01tnG8hhqQBUGic-nQ; SID=DQAAAOMAAACA9Ls5H38viyAdoOklcngRVIehvz7FuhZ7VjBFRk8dCRZvIFg_iazcIQVlG86WfB3J49_IHuntng0S7YOro1dSrYpUX_vKf3GayhSOqvsvRcgoU2xmh_4YSIUXdKQhSUCa8f8dC7bdqCkREDINsMyZTGvCo7oln5djO20o388xWvlXxU9tTXdBDZnvuuoy30kWOQWRKdxpWBycNePtyyDpgDLDtc2IR4mdQrj1IwkVeblT8fwgKQ8kbtMriVpxCRnMrLllV6b55T8TYzWM99rKsCj-DoKokuvOPGsY7pTvX4Ymlf0KVK750ucNfUt8mtM; HSID=AmbjVFQG3HqJY6ZuZ; SSID=AvD4MxG9JVApQjntq; APISID=4DVrq2NUKDMqKZom/ALli6pwzzt7nHyPBH; SAPISID=Mz2aVNqjt4gRTzWU/AgJGzqMyNX7hHzMcY; S=grandcentral=PYMljq_EubSM6OtDobUI4A";
            var dataStream = request.GetRequestStream();
            dataStream.Write(byteArray, 0, byteArray.Length);
            dataStream.Close();
            var response = request.GetResponse();
            dataStream = response.GetResponseStream();
            var reader = new StreamReader(dataStream);
            string responseFromServer = reader.ReadToEnd();
            reader.Close();
            dataStream.Close();
            response.Close();
            return FromJson(responseFromServer.Substring(5).Trim());
        }
    }


    [Serializable]
    public class Status
    {

        public int Value;

        //Empty Constructor
        public Status() { }

    }


    [Serializable]
    public class Contact
    {

        public object Id;
        public string Phone_number_formatted;
        public string Phone_number;
        public int Phone_type;
        public string Name;

        //Empty Constructor
        public Contact() { }

    }


    [Serializable]
    public class Phone_call
    {

        public string Id;
        public string Message_text;
        public int Status;
        public int Coarse_type;
        public string Did;
        public object Start_time;
        public int Transcript_status;
        public int Type;
        public Contact Contact;

        //Empty Constructor
        public Phone_call() { }

    }


    [Serializable]
    public class Conversation
    {

        public string Id;
        public bool Read;
        public string[] Label;
        public object Conversation_time;
        public Phone_call[] Phone_call;

        //Empty Constructor
        public Conversation() { }

    }


    [Serializable]
    public class Conversations_response
    {

        public Status Status;
        public Conversation[] Conversation;

        //Empty Constructor
        public Conversations_response() { }

    }


    [Serializable]
    public class Status2
    {

        public int Status;

        //Empty Constructor
        public Status2() { }

    }


    [Serializable]
    public class Label
    {

        public object Last_modified_timestamp;
        public string LabelName;
        public int Unread_count;
        public int Total_count;

        //Empty Constructor
        public Label() { }

    }


    [Serializable]
    public class Account_status
    {

        public int Max_balance;
        public string Displayable_max_balance;
        public int Paid_credit;
        public Status2 Status;
        public string Primary_did;
        public string[] Displayable_valid_amount;
        public Label[] Label;
        public string Displayable_account_balance;
        public bool Active_in_use;
        public int Type;
        public int[] Valid_amount;
        public int Account_balance;

        //Empty Constructor
        public Account_status() { }

    }

}
//Json Mapping End
